name: Deploy my-poem-website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install pnpm -g
        
      - name: Install dependencies
        run: pnpm install

      - name: Set up Git config
        run: |
          git config --global user.email "854806732@qq.com"
          git config --global user.name "eveningwater"
      - name: Configure Git to use token
        run: git remote set-url origin https://eveningwater:${{ secrets.ANCIENT_CHINESE_GH_TOKEN }}@github.com/eveningwater/ancient-chinese-website.git

      - name: Build the project
        run: pnpm run docs:build

      - name: Deploy to GitHub Pages
        run: pnpm run release
        env:
          GH_TOKEN: ${{ secrets.ANCIENT_CHINESE_GH_TOKEN }}
